export const IPHONE_MODELS = [
  'iPhone 17 Pro Max',
  'iPhone 17 Pro',
  'iPhone 17 Plus',
  'iPhone 17',
  'iPhone 16 Pro Max',
  'iPhone 16 Pro',
  'iPhone 16 Plus',
  'iPhone 16',
  'iPhone 15 Pro Max',
  'iPhone 15 Pro',
  'iPhone 15 Plus',
  'iPhone 15',
  'iPhone 14 Pro Max',
  'iPhone 14 Pro',
  'iPhone 14 Plus',
  'iPhone 14',
  'iPhone 13 Pro Max',
  'iPhone 13 Pro',
  'iPhone 13 Mini',
  'iPhone 13',
  'iPhone 12 Pro Max',
  'iPhone 12 Pro',
  'iPhone 12 Mini',
  'iPhone 12',
  'iPhone 11 Pro Max',
  'iPhone 11 Pro',
  'iPhone 11',
  'iPhone XS Max',
  'iPhone XS',
  'iPhone XR',
  'iPhone X',
  'iPhone 8 Plus',
  'iPhone 8',
  'iPhone 7 Plus',
  'iPhone 7',
  'iPhone SE (2nd gen)',
  'iPhone SE (1st gen)',
  'iPhone 6s Plus',
  'iPhone 6s',
  'iPhone 6 Plus',
  'iPhone 6',
  'iPhone 5s',
  'iPhone 5c',
  'iPhone 5',
  'iPhone 4s',
  'iPhone 4',
  'iPhone 3GS',
  'iPhone 3G',
  'iPhone'
]

export const IPHONE_COLORS = [
  'Desert Titanium',
  'Midnight Black',
  'Arctic Blue',
  'Rose Gold',
  'Natural Titanium',
  'Space Black',
  'Space Gray',
  'Gold',
  'Silver',
  'Blue',
  'Blue Titanium',
  'Red',
  'Product Red',
  'Green',
  'Purple',
  'Deep Purple',
  'White',
  'Black',
  'Starlight',
  'Pink',
  'Yellow',
  'Coral',
  'Pacific Blue',
  'Graphite',
  'Alpine Green',
  'Sierra Blue',
  'Jet Black',
  'Matte Black',
  'Jet White',
  'Matte White',
  'Titanium Blue',
  'Titanium Natural',
  'Titanium White',
  'Titanium Black'
]

export const IPHONE_STORAGE = [
  '64GB',
  '128GB',
  '256GB',
  '512GB',
  '1TB',
  '2TB'
]

export const CONDITIONS = ['New', 'Refurbished', 'Used']

export const PAYMENT_METHODS = ['Cash', 'Mobile Money', 'Card', 'Split Payment']

